### ISSUE TITLE
findView-created views don't extend PositronicHandlers

### ISSUE THREAD

**Issue by haxney** [rst/positronic_net#1]
The following code:

``` scala
class MyActivity extends PositronicActivity with TypedActivity {
onCreate {
    findView(TR.button_id).onClick {}
  }
}
```

causes Eclipse to complain, since an `android.widget.Button` is returned by `findView()`, rather than a `PositronicButton`. Some implicit conversions would probably help, or I may be doing something wrong.

Thanks for a great project!

**Comment by haxney** [comment]
Oh. You need to have e.g. `org.positronicnet.ui.PositronicButton` in your `res/layout/activity.xml`, rather than simply `Button`. Makes sense now.

This should probably be documented :)

**Comment by rst** [comment]
Indeed.  Documentation is needed generally.  The sample apps (the bundled one and the sample apps in my top-level repos) are there as a stopgap, but I'm under no illusion that they're adequate long-term.  But as of yet, there are some things I'm hoping to see as major components (e.g. the stuff now under development on the reflective_orm branch) which aren't quite there yet, and I'm hoping to have that stuff in place in some form before I start writing tutorials.

Thanks for giving it a try!
