### ISSUE TITLE
Error compiling with Scala 2.8.2.final.

### ISSUE THREAD

**Issue by wpoosanguansit** [rst/positronic_net#3]
Hi, 

Thank you for putting the code out.  I am trying out your lib by compiling it against 2.8.2.  And this is the error I get.

[error] /Volumes/space/Projects/Java/positronic_net/src/main/scala/ui/ResourceId.scala:27: value reduce is not a member of Array[String]
[error] /Volumes/space/Projects/Java/positronic_net/src/main/scala/ui/ResourceId.scala:27: value reduce is not a member of Array[String]
[error]         components.slice(0, numComponents).reduce(_ + "." + _)
[error]         components.slice(0, numComponents).reduce(_ + "." + _)

I looked at the source and tried to change that to map but still didn't get it to work.  It is just one place that is failing.  So I hope you would make the change to support the 2.8.2 code.  Thanks for your help.

Watt P.

**Comment by rst** [comment]
What I'd expect to work there would be 'reduceLeft' (or 'reduceRight'; in this context, they're equivalent).  If that's the only issue, I could try to have a patch on trunk later today...

**Comment by rst** [comment]
Well, that's the only _obvious_ issue.  (With that dink, and with ScalaTest downgraded in the build file to 1.5.1, everything builds and the tests pass.)  So, you should be able to at least kick the tires now.

BTW, Scala 2.9.0-1 seems to be working for me, though I haven't tried anything more recent.  Is there any particular advantage to using the older version?  (If it's just a matter of not shoveling through a round of upgrades to your local toolchain, I can certainly understand that, too...)

**Comment by wpoosanguansit** [comment]
Thank you for your help.  Things seem to compile fine with the change.  The reason I am still on the 2.8.2 branch is because I am using treeshaker and eclipse.  And  2.9.1 generates different byte code with unrecognized op code and break the build, unfortunately.  Still can't fanthom what would be the reason to change the bytecode.

Thanks again for your help.
