### ISSUE TITLE
Incorrect QueueRunnerThread implementation

### ISSUE THREAD

**Issue by th0br0** [rst/positronic_net#8]
The current QueueRunnerThread implementation returns a handler to the future upon creation.

However, this handler is not being passed an instance of the HandlerThread's looper!
The looper is only available once HandlerThread.onLooperPrepared has been called. 

``` scala
class QueueRunnerThread
  extends HandlerThread( this.toString )
{
  override def onLooperPrepared() = {
    threadHandlerFut.succeed( new Handler(getLooper()) )
  }
}
```

**Comment by rst** [comment]
I believe this is now fixed on master... let me know if it still looks off.  Thanks!
