### ISSUE TITLE
Would there be any update to the code?

### ISSUE THREAD

**Issue by wpoosanguansit** [rst/positronic_net#9]
Hi, thanks for your work.  I experimented with you code a while back and I quite like it.  And it looks like the code has not been updated for a while.  Would you plan to by any chance?  Or if this is already abandoned.  Thanks again for your help and work.

**Comment by rst** [comment]
I'm not actively working on it right now.  There is a 'scala210' branch, which builds on 2.10, and passes its tests -- but with some deprecation warnings.  I'd certainly take pull requests to fix those up.  (Or, of course, you could clone it.)
